---
services:
  blockchain-esgi-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blockchain
    depends_on:
      rabbitmq:
          condition: service_healthy
    env_file:
      - .env
    volumes:
      - "./code:/home/user/BlockChain-ESGI"
    network_mode: "host"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    network_mode: "host"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
...
