# Use the official Consul image
FROM hashicorp/consul:1.19.0

# Add consul.hcl configuration file
COPY ./consul-conf/consul.hcl /consul/config/consul.hcl
COPY ./consul-conf/consul-entrypoint.sh /consul/consul-entrypoint.sh
COPY ./consul-conf/healthcheck.sh /consul/
RUN apk update && apk add tailscale jq

RUN chmod +x /consul/consul-entrypoint.sh /consul/healthcheck.sh

CMD ["sh","/consul/consul-entrypoint.sh"]
