---
services:
  blockchain-esgi-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blockchain
    depends_on:
      rabbitmq:
          condition: service_healthy
    env_file:
      - .env
    volumes:
      - "./code:/home/user/BlockChain-ESGI"
    network_mode: "host"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    container_name: rabbitmq
    depends_on:
      consul:
          condition: service_healthy
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_ERLANG_COOKIE: "test"
    volumes:
      - /run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    network_mode: "host"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 20s
      retries: 5

  consul:
    build:
      context: .
      dockerfile: Dockerfile-consul
    container_name: consul
    network_mode: host
    volumes:
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
    healthcheck:
      test: ["CMD", "./consul/healthcheck.sh"]      
      interval: 10s
      timeout: 10s
      retries: 5
...
