---
services:
  blockchain-esgi-dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - "./code:/home/user/BlockChain-ESGI"
    network_mode: "service:tailscale"
    depends_on: 
      - tailscale
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile-tailscale
    env_file: env
...
