FROM python:alpine3.19

RUN apk update && \
    apk add git openssh gcc python3-dev libc-dev

RUN pip install --upgrade pip

RUN adduser --disabled-password -u 1000 user && \
    mkdir -p /home/user/.ssh

# COPY ./github_keys/id_rsa_github /home/user/.ssh
# COPY ./github_keys/id_rsa_github.pub /home/user/.ssh

RUN chown -R 1000:1000 /home/user/.ssh

#RUN chmod 400 /home/user/.ssh/id_rsa_github

COPY ./entrypoint-dev.sh /home/user/entrypoint-dev.sh

RUN chown -R 1000:1000 /home/user/entrypoint-dev.sh

COPY ./code/requirements.txt .

RUN pip install -r requirements.txt

USER user

WORKDIR /home/user

ENTRYPOINT ["/bin/ash", "/home/user/entrypoint-dev.sh"]