---
services:
  blockchain-esgi-dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    container_name: blockchain
    restart: always
    volumes:
      - "./code:/home/user/BlockChain-ESGI"
    network_mode: "host"
...
